name: app-manually-created
services:
    backend:
        build:
            context: ./backend
        environment:
            ASPNETCORE_ENVIRONMENT: UAT
        depends_on:
            - db
        ports:
        - target: 8080
          published: "8082"

    frontend:
        build:
            context: ./frontend
        environment:
            ENVIRONMENT: UAT
        depends_on:
            - backend
        ports:
        - target: 3000
          published: "3233"

    db:
      image: mcr.microsoft.com/mssql/server:2022-latest
      env_file:
        - ./backend/.env
      ports:
        - target: 1433
          published: "1433"
