apiVersion: score.dev/v1b1

metadata:
  name: backend

service:
  ports:
    backend:
      port: 8082
      targetPort: 8080

containers:
  backend:
    image: ./backend
    variables:
      "ENVIRONMENT": Development