apiVersion: score.dev/v1b1

metadata:
  name: database

service:
  ports:
    database:
      port: 1433
      targetPort: 1433

containers:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    variables:
      ENVIRONMENT: UAT