apiVersion: score.dev/v1b1

metadata:
  name: frontend

service:
  ports:
    frontend:
      port: 3233
      targetPort: 3000

containers:
  frontend:
    image: default
    variables:
      ENVIRONMENT: UAT