apiVersion: score.dev/v1b1

metadata:
  name: aspnetcore

service:
  ports:
    web:
      port: 5348
      targetPort: 5348

containers:
  aspnetcore:
    image: .
    variables:
      "ASPNETCORE_ENVIRONMENT": Development