apiVersion: score.dev/v1b1

metadata:
  name: application

service:
  ports:
    aspnetcore:
      port: 5348
      targetPort: 5348
    backend:
      port: 8002
      targetPort: 8002

containers:
  aspnetcore:
    image: ./aspnetcore
    variables:
      "ASPNETCORE_ENVIRONMENT": Development
  backend:
    image: ./backend
    variables:
      "ENVIRONMENT": Development