apiVersion: score.dev/v1b1

metadata:
  name: frontend

service:
  ports:
    frontend:
      port: 5348
      targetPort: 5348

containers:
  frontend:
    image: ./aspnetcore
    variables:
      "ASPNETCORE_ENVIRONMENT": Development